### ISSUE TITLE
filesystem_folder dependency

### ISSUE THREAD

**Issue by 532910** [jspricke/radicale-storage#5]
If filesystem_folder is not defined the URL will be http://localhost:5232/var/lib/radicale/.reminders/ and will give
```The requested resource could not be found.```

**Comment by jspricke** [comment]
`filesystem_folder` is set to `/var/lib/radicale/collections` by default in Radicale, https://github.com/Kozea/Radicale/blob/master/radicale/config.py#L165. This seems like a valid assumption, though not an optimal one, as commented in #4. Given that radicale-remind uses this variable since a long time, and it could be a valid path, I don't see a way to enforce a stricter dependency.

Also note that the URL will probably be something like http://localhost:5232/var/lib/radicale/collections/$USER/.reminders/.
